/**
 * HomeLii Security Automation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.wordnik.client.api

import com.wordnik.client.model.Sensor
import com.wordnik.client.model.SensorUpdate

import java.io.File

import org.scalatra.{ TypedParamSupport, ScalatraServlet }
import org.scalatra.swagger._
import org.json4s._
import org.json4s.JsonDSL._
import org.scalatra.json.{ JValueResult, JacksonJsonSupport }
import org.scalatra.servlet.{FileUploadSupport, MultipartConfig, SizeConstraintExceededException}

import scala.collection.JavaConverters._

class SensorApi (implicit val swagger: Swagger) extends ScalatraServlet
    with FileUploadSupport
    with JacksonJsonSupport
    with SwaggerSupport {
  protected implicit val jsonFormats: Formats = DefaultFormats

  protected val applicationDescription: String = "SensorApi"
  override protected val applicationName: Option[String] = Some("/v2/Sensor")

  before() {
    contentType = formats("json")
    response.headers += ("Access-Control-Allow-Origin" -> "*")
  }
  

  val addSensorOperation = (apiOperation[Unit]("addSensor")
      summary "Add a new Sensor"
      parameters(bodyParam[Sensor]("body").description(""))
  )

  post("/sensor",operation(addSensorOperation)) {
    
    
          val body = parsedBody.extract[Sensor]

    println("body: " + body)
  }

  

  val updateSensorOperation = (apiOperation[Unit]("updateSensor")
      summary "Update existing sensor in device"
      parameters(pathParam[String]("serielNumber").description(""), bodyParam[SensorUpdate]("body").description(""))
  )

  put("/sensor/:seriel_number",operation(updateSensorOperation)) {
    
    
      val serielNumber = params.getOrElse("serielNumber", halt(400))
    
    println("serielNumber: " + serielNumber)
    
    
          val body = parsedBody.extract[SensorUpdate]

    println("body: " + body)
  }

}
