/**
 * HomeLii Security Automation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.wordnik.client.model


case class Event (
  /* ON/Off state of Play_Alarm in device */
  onoff: Option[String],
  /* Set access point name of the network in a device */
  apn: Option[String],
  /* set apn name for the access point of a network */
  apn_name: Option[String],
  /* set a password to the apn of selected network */
  pwd: Option[String],
  /* configure gprs ip to the device to send signals */
  ip: Option[String],
  /* configure gprs port to the device to send signals */
  port: Option[String],
  /* set user_id to the device */
  user_id: Option[String],
  /* Add a group no. to the device */
  group: Option[String],
  /* Set a 10 digit Number for configuration */
  number: Option[String],
  /* set delay time for arming mode in device */
  alarming_delay: Option[String],
  /* set delay time for disarming mode in device */
  disalarming_delay: Option[String],
  /* set alarm time in the device */
  time: Option[String],
  /* set attribute to the zone numbers */
  attribute: Option[String]
)
